import type { application, Node } from "claygl";
import type * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import type { StudioConfiguration } from "@ai-estimate-studio/domain";

/**
 * Display assets generated by scripts/generate-studio-cad.py.
 *
 * The CAD kernel never runs in the browser. These small GLBs are immutable
 * presentation assets, selected only for exact catalog configurations. Any
 * configuration without a matching asset keeps the procedural renderer.
 */
export type StudioCadAssetPlan = Readonly<{
  id: string;
  baseCode: StudioConfiguration["baseCode"];
  wallCodes: readonly string[];
  path: string;
}>;

export const studioCadAssetPlans: readonly StudioCadAssetPlan[] = Object.freeze(
  [
    {
      id: "p1-m1",
      baseCode: "P1",
      wallCodes: Object.freeze(["M1"]),
      path: "/assets/models/studio/mobup-studio-p1-m1.glb",
    },
    {
      id: "p2-m7",
      baseCode: "P2",
      wallCodes: Object.freeze(["M7"]),
      path: "/assets/models/studio/mobup-studio-p2-m7.glb",
    },
    {
      id: "p3-m8",
      baseCode: "P3",
      wallCodes: Object.freeze(["M8"]),
      path: "/assets/models/studio/mobup-studio-p3-m8.glb",
    },
    {
      id: "p4-m1-m8",
      baseCode: "P4",
      wallCodes: Object.freeze(["M1", "M8"]),
      path: "/assets/models/studio/mobup-studio-p4-m1-m8.glb",
    },
  ],
);

const publicAssetPath = (path: string) =>
  `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}${path}`;

export function resolveStudioCadAsset(
  configuration: StudioConfiguration,
): StudioCadAssetPlan | undefined {
  const wallCodes = configuration.walls.map((wall) => wall.code);
  return studioCadAssetPlans.find(
    (plan) =>
      plan.baseCode === configuration.baseCode &&
      plan.wallCodes.length === wallCodes.length &&
      plan.wallCodes.every((code, index) => code === wallCodes[index]),
  );
}

function prepareThreeCadAsset(root: THREE.Object3D, plan: StudioCadAssetPlan) {
  root.name = `cad-studio-${plan.id}`;
  root.traverse((object) => {
    object.castShadow = true;
    object.receiveShadow = true;
  });
}

/** Load an exact CAD variant into a Three.js model root. */
export async function loadThreeStudioCadAsset(
  parent: THREE.Object3D,
  configuration: StudioConfiguration,
): Promise<THREE.Object3D | undefined> {
  const plan = resolveStudioCadAsset(configuration);
  if (!plan) return undefined;
  try {
    const result = await new GLTFLoader().loadAsync(publicAssetPath(plan.path));
    prepareThreeCadAsset(result.scene, plan);
    parent.add(result.scene);
    return result.scene;
  } catch {
    // A static deployment can still use the validated procedural fallback if
    // an optional CAD asset is unavailable or blocked by a stale CDN cache.
    return undefined;
  }
}

function prepareClayCadAsset(root: Node, plan: StudioCadAssetPlan): void {
  root.name = `cad-studio-${plan.id}`;
  root.traverse((child) => {
    const renderable = child as Node & {
      castShadow?: boolean;
      receiveShadow?: boolean;
    };
    renderable.castShadow = true;
    renderable.receiveShadow = true;
  });
}

/** Load an exact CAD variant into a ClayGL model root. */
export async function loadClayStudioCadAsset(
  app: application.App3D,
  parent: Node,
  configuration: StudioConfiguration,
): Promise<Node | undefined> {
  const plan = resolveStudioCadAsset(configuration);
  if (!plan) return undefined;
  try {
    const result = await app.loadModel(
      publicAssetPath(plan.path),
      {
        shader: "clay.standardMR",
        waitTextureLoaded: true,
        textureConvertToPOT: true,
      },
      parent,
    );
    if (!result.rootNode) return undefined;
    prepareClayCadAsset(result.rootNode, plan);
    return result.rootNode;
  } catch {
    // Keep the procedural model visible when ClayGL cannot decode the GLB.
    return undefined;
  }
}

const THREE_STRUCTURAL_GROUPS = new Set(["foundation", "roof", "walls"]);
const CLAY_STRUCTURAL_NODES = new Set([
  "foundation-slab",
  "foundation-edge",
  "flat-roof",
  "roof-fascia",
  "walls",
]);

/** Hide only the duplicate procedural structure; accessories/analysis remain. */
export function hideThreeProceduralStudioStructure(root: THREE.Object3D): void {
  root.children.forEach((child) => {
    if (THREE_STRUCTURAL_GROUPS.has(child.name)) child.visible = false;
  });
}

/** Hide only the duplicate procedural structure in the ClayGL tree. */
export function hideClayProceduralStudioStructure(root: Node): void {
  root.children().forEach((child) => {
    if (CLAY_STRUCTURAL_NODES.has(child.name)) {
      (child as Node & { invisible?: boolean }).invisible = true;
    }
  });
}
